# Generated by Django 6.0.4 on 2026-07-10 17:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.PositiveBigIntegerField(editable=False, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=40, unique=True)),
                ('previous_slug', models.SlugField(blank=True, max_length=40, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('website_url', models.CharField(blank=True, default='', max_length=255)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('delete_after', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workspaces', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.PositiveBigIntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=40)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('product_url', models.CharField(blank=True, default='', max_length=500)),
                ('allowed_domains', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('setup_required', 'Setup required'), ('active', 'Active'), ('no_recent_data', 'No recent data')], default='setup_required', max_length=32)),
                ('first_production_event_at', models.DateTimeField(blank=True, null=True)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', help_text='Project timezone for session date filtering', max_length=50)),
                ('tracking_capture', models.CharField(default='analytics,recording', max_length=32)),
                ('page_structure_guidance', models.CharField(blank=True, default='', max_length=500)),
                ('page_naming_state', models.CharField(choices=[('not_stable', 'Not stable'), ('stable', 'Stable')], default='not_stable', max_length=16)),
                ('page_naming_state_changed_at', models.DateTimeField(blank=True, null=True)),
                ('page_naming_first_event_at', models.DateTimeField(blank=True, null=True)),
                ('lifecycle_status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=16)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('delete_after', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('removed', 'Removed')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='projects.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceOpenAICredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_api_key', models.TextField()),
                ('key_last_four', models.CharField(blank=True, default='', max_length=4)),
                ('validation_status', models.CharField(choices=[('unchecked', 'Not checked'), ('valid', 'Valid'), ('invalid', 'Invalid'), ('unavailable', 'Temporarily unavailable')], default='unchecked', max_length=16)),
                ('validation_error_code', models.CharField(blank=True, default='', max_length=32)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_workspace_openai_credentials', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='openai_credential', to='projects.workspace')),
            ],
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['archived_at'], name='projects_workspace_arch_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['workspace'], name='projects_workspace_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['workspace', 'lifecycle_status'], name='projects_ws_lifecycle_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('workspace', 'slug'), name='projects_workspace_slug_unique'),
        ),
        migrations.AddIndex(
            model_name='workspacemembership',
            index=models.Index(fields=['user', 'status', 'removed_at'], name='projects_member_user_state_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacemembership',
            index=models.Index(fields=['workspace', 'role', 'status'], name='projects_member_ws_role_idx'),
        ),
        migrations.AddConstraint(
            model_name='workspacemembership',
            constraint=models.UniqueConstraint(fields=('workspace', 'user'), name='projects_workspace_user_unique'),
        ),
        migrations.AddConstraint(
            model_name='workspacemembership',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('removed_at__isnull', True), ('status', 'active')), models.Q(('removed_at__isnull', False), ('status', 'removed')), _connector='OR'), name='projects_membership_status_removed_consistent'),
        ),
    ]
