# Generated by Django 6.0.4 on 2026-08-06 15:21

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='analytics_facts_revision',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='filtered_analytics_revision',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='tracking_capture',
            field=models.CharField(default='analytics', max_length=32),
        ),
        migrations.CreateModel(
            name='CompanyAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('attribute_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('money', 'Money'), ('date', 'Date'), ('boolean', 'Boolean'), ('single_select', 'Single select')], max_length=20)),
                ('position', models.PositiveIntegerField(default=0)),
                ('number_format', models.CharField(blank=True, choices=[('plain', 'Plain number'), ('percentage', 'Percentage')], default='', max_length=16)),
                ('decimal_places', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('AED', 'AED'), ('AUD', 'AUD'), ('BGN', 'BGN'), ('BRL', 'BRL'), ('CAD', 'CAD'), ('CHF', 'CHF'), ('CNY', 'CNY'), ('CZK', 'CZK'), ('DKK', 'DKK'), ('HKD', 'HKD'), ('HUF', 'HUF'), ('ILS', 'ILS'), ('INR', 'INR'), ('JPY', 'JPY'), ('KRW', 'KRW'), ('MXN', 'MXN'), ('NOK', 'NOK'), ('NZD', 'NZD'), ('PLN', 'PLN'), ('RON', 'RON'), ('SAR', 'SAR'), ('SEK', 'SEK'), ('SGD', 'SGD'), ('TRY', 'TRY'), ('UAH', 'UAH'), ('ZAR', 'ZAR')], default='', max_length=3)),
                ('money_display', models.CharField(blank=True, choices=[('compact', 'Compact'), ('full', 'Full')], default='', max_length=16)),
                ('boolean_display', models.CharField(blank=True, choices=[('yes_no', 'Yes / No'), ('checkmark_dash', 'Checkmark / Dash')], default='', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_attributes', to='projects.project')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CompanyAttributeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('color', models.CharField(choices=[('red', 'Red'), ('orange', 'Orange'), ('amber', 'Amber'), ('yellow', 'Yellow'), ('lime', 'Lime'), ('green', 'Green'), ('emerald', 'Emerald'), ('teal', 'Teal'), ('cyan', 'Cyan'), ('sky', 'Sky'), ('blue', 'Blue'), ('indigo', 'Indigo'), ('violet', 'Violet'), ('purple', 'Purple'), ('pink', 'Pink'), ('slate', 'Slate')], default='cyan', max_length=16)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='projects.companyattribute')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CompanyAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(max_length=255)),
                ('text_value', models.TextField(blank=True, null=True)),
                ('decimal_value', models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True)),
                ('date_value', models.DateField(blank=True, null=True)),
                ('boolean_value', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='projects.companyattribute')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='projects.companyattributeoption')),
            ],
        ),
        migrations.CreateModel(
            name='CompanySegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('definition', models.JSONField(default=dict)),
                ('needs_review', models.BooleanField(default=False)),
                ('pending_attribute_deletions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_segments', to='projects.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_segments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsFilterState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.JSONField(blank=True, default=dict)),
                ('state', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_filter_states', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_filter_states', to=settings.AUTH_USER_MODEL)),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filter_states', to='projects.companysegment')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsPageState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(max_length=64)),
                ('state', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_page_states', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_page_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'user', 'page_key'), name='projects_analytics_page_state_uniq')],
            },
        ),
        migrations.AddIndex(
            model_name='companyattribute',
            index=models.Index(fields=['project', 'position'], name='projects_attr_proj_pos_idx'),
        ),
        migrations.AddConstraint(
            model_name='companyattribute',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('project'), name='projects_attr_project_name_ci_uniq'),
        ),
        migrations.AddIndex(
            model_name='companyattributeoption',
            index=models.Index(fields=['attribute', 'position'], name='projects_opt_attr_pos_idx'),
        ),
        migrations.AddConstraint(
            model_name='companyattributeoption',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('label'), models.F('attribute'), name='projects_attr_option_label_ci_uniq'),
        ),
        migrations.AddIndex(
            model_name='companyattributevalue',
            index=models.Index(fields=['company_id'], name='projects_attrval_company_idx'),
        ),
        migrations.AddIndex(
            model_name='companyattributevalue',
            index=models.Index(fields=['attribute', 'decimal_value'], name='projects_attrval_decimal_idx'),
        ),
        migrations.AddIndex(
            model_name='companyattributevalue',
            index=models.Index(fields=['attribute', 'date_value'], name='projects_attrval_date_idx'),
        ),
        migrations.AddIndex(
            model_name='companyattributevalue',
            index=models.Index(fields=['attribute', 'boolean_value'], name='projects_attrval_bool_idx'),
        ),
        migrations.AddIndex(
            model_name='companyattributevalue',
            index=models.Index(fields=['attribute', 'option'], name='projects_attrval_option_idx'),
        ),
        migrations.AddConstraint(
            model_name='companyattributevalue',
            constraint=models.UniqueConstraint(fields=('attribute', 'company_id'), name='projects_attr_value_company_uniq'),
        ),
        migrations.AddConstraint(
            model_name='companyattributevalue',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('boolean_value__isnull', True), ('date_value__isnull', True), ('decimal_value__isnull', True), ('option__isnull', True), ('text_value__isnull', False)), models.Q(('boolean_value__isnull', True), ('date_value__isnull', True), ('decimal_value__isnull', False), ('option__isnull', True), ('text_value__isnull', True)), models.Q(('boolean_value__isnull', True), ('date_value__isnull', False), ('decimal_value__isnull', True), ('option__isnull', True), ('text_value__isnull', True)), models.Q(('boolean_value__isnull', False), ('date_value__isnull', True), ('decimal_value__isnull', True), ('option__isnull', True), ('text_value__isnull', True)), models.Q(('boolean_value__isnull', True), ('date_value__isnull', True), ('decimal_value__isnull', True), ('option__isnull', False), ('text_value__isnull', True)), _connector='OR'), name='projects_attr_value_one_typed'),
        ),
        migrations.AddIndex(
            model_name='companysegment',
            index=models.Index(fields=['project', 'user', 'name'], name='projects_segment_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='companysegment',
            index=models.Index(fields=['project', 'user', 'needs_review'], name='projects_segment_review_idx'),
        ),
        migrations.AddConstraint(
            model_name='companysegment',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('project'), models.F('user'), name='projects_segment_owner_name_ci_uniq'),
        ),
        migrations.AddConstraint(
            model_name='companysegment',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('project'), condition=models.Q(('user__isnull', True)), name='projects_segment_seeded_name_ci_uniq'),
        ),
        migrations.AddConstraint(
            model_name='analyticsfilterstate',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='projects_analytics_filter_state_uniq'),
        ),
    ]
