# Generated by Django 5.0.2 on 2026-02-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_chatgptkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgptkey',
            name='need_to_check',
            field=models.BooleanField(default=False),
        ),
    ]
