# Generated by Django 5.0.2 on 2026-02-25 14:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Suggested values: gpt-4o, gpt-4o-mini, gpt-4, gpt-3.5-turbo', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('original_title', models.CharField(default='', max_length=255, verbose_name='Original title')),
                ('_title', models.CharField(blank=True, db_column='title', default='', max_length=255, verbose_name='AI generated title')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('color_index', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SafeInputRegexTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('pattern', models.CharField(max_length=500, unique=True)),
                ('description', models.TextField()),
                ('the_order', models.PositiveSmallIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('keep_prefix_chars', models.PositiveSmallIntegerField(default=0, help_text='Number of characters to keep visible at start')),
                ('keep_prefix_digits', models.PositiveSmallIntegerField(default=0, help_text='Number of digits to keep visible at start')),
                ('hide_after_delimiter', models.CharField(blank=True, help_text="Delimiter to hide everything after (e.g., '@' for emails)", max_length=10, null=True)),
                ('mask_type', models.CharField(choices=[('prefix_only', 'Keep prefix only (most secure)'), ('prefix_suffix', 'Keep prefix and suffix (less secure)')], default='custom', help_text='Masking strategy to use', max_length=20)),
            ],
            options={
                'ordering': ['the_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TitlePrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('prompt_text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectNormalizationFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.FloatField(help_text='Normalization factor (k) for bubble size calculations')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalization_factors', to='projects.project')),
            ],
            options={
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_id', models.CharField(help_text='Unique browser tab identifier', max_length=36, null=True)),
                ('event_type', models.PositiveSmallIntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', models.JSONField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tracker.page')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tracker.session')),
            ],
        ),
        migrations.CreateModel(
            name='BubbleCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Hour and Minute')),
                ('size', models.PositiveSmallIntegerField(verbose_name='Bubble size')),
                ('clicks', models.PositiveSmallIntegerField(verbose_name='Click count')),
                ('mouse_moves', models.PositiveSmallIntegerField(verbose_name='Mouse movements')),
                ('key_strokes', models.PositiveSmallIntegerField(verbose_name='Key strokes')),
                ('seconds_spent', models.PositiveIntegerField(default=0, verbose_name='Seconds spent on page')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bubbles', to='tracker.page')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bubbles', to='tracker.session')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('visitor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visitor_guid', models.UUIDField(blank=True, help_text='Visitor ID from browser', null=True)),
                ('first_visit', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'unique_together': {('visitor_guid', 'project')},
            },
        ),
        migrations.AddField(
            model_name='session',
            name='visitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tracker.visitor'),
        ),
    ]
