# Generated by Django 5.0.2 on 2025-07-08 10:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Suggested values: gpt-4o, gpt-4o-mini, gpt-4, gpt-3.5-turbo', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('original_title', models.CharField(default='', max_length=255, verbose_name='Original title')),
                ('_title', models.CharField(blank=True, db_column='title', default='', max_length=255, verbose_name='AI generated title')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('color_index', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='TitlePrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('prompt_text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', models.JSONField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tracker.page')),
            ],
        ),
        migrations.CreateModel(
            name='BubbleCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Hour and Minute')),
                ('size', models.PositiveSmallIntegerField(verbose_name='Bubble size')),
                ('clicks', models.PositiveSmallIntegerField(verbose_name='Click count')),
                ('mouse_moves', models.PositiveSmallIntegerField(verbose_name='Mouse movements')),
                ('key_strokes', models.PositiveSmallIntegerField(verbose_name='Key strokes')),
                ('seconds_spent', models.PositiveIntegerField(default=0, verbose_name='Seconds spent on page')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bubbles', to='tracker.page')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectNormalizationFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.FloatField(help_text='Normalization factor (k) for bubble size calculations')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalization_factors', to='projects.project')),
            ],
            options={
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_url', models.URLField()),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='tracker.session'),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('session', 'url')},
        ),
    ]
