# Generated by Django 6.0.4 on 2026-07-10 17:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafeInputRegexTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('pattern', models.CharField(max_length=500, unique=True)),
                ('description', models.TextField()),
                ('the_order', models.PositiveSmallIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('keep_prefix_chars', models.PositiveSmallIntegerField(default=0, help_text='Number of characters to keep visible at start')),
                ('keep_prefix_digits', models.PositiveSmallIntegerField(default=0, help_text='Number of digits to keep visible at start')),
                ('hide_after_delimiter', models.CharField(blank=True, help_text="Delimiter to hide everything after (e.g., '@' for emails)", max_length=10, null=True)),
                ('mask_type', models.CharField(choices=[('prefix_only', 'Keep prefix only (most secure)'), ('prefix_suffix', 'Keep prefix and suffix (less secure)'), ('prefix_digits', 'Keep leading digits'), ('custom', 'Custom masking rules')], default='custom', help_text='Masking strategy to use', max_length=20)),
            ],
            options={
                'ordering': ['the_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TitlePrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('bootstrap_page_naming_prompt', models.TextField(blank=True, default='')),
                ('bootstrap_page_naming_openai_model', models.CharField(blank=True, default='', help_text='OpenAI model used for bootstrap page naming prompt.', max_length=100)),
                ('hourly_unstable_prompt', models.TextField(blank=True, default='')),
                ('hourly_unstable_openai_model', models.CharField(help_text='OpenAI model used for the hourly unstable prompt.', max_length=100)),
                ('daily_stable_prompt', models.TextField(blank=True, default='')),
                ('daily_stable_openai_model', models.CharField(help_text='OpenAI model used for the daily stable prompt.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visitor_guid', models.UUIDField(blank=True, help_text='Visitor ID from browser', null=True)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('company_id', models.CharField(blank=True, max_length=255, null=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_sessions', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectNormalizationFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.FloatField(help_text='Normalization factor (k) for bubble size calculations')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalization_factors', to='projects.project')),
            ],
            options={
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPageNamingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('hourly_unstable', 'Hourly unstable'), ('daily_stable', 'Daily stable'), ('hourly_backfill', 'Hourly title backfill')], max_length=32)),
                ('phase', models.CharField(blank=True, choices=[('bootstrap', 'Bootstrap'), ('incremental', 'Incremental'), ('stable', 'Stable'), ('backfill', 'Backfill')], default='', max_length=16)),
                ('status', models.CharField(choices=[('success', 'Success'), ('skipped', 'Skipped'), ('failed', 'Failed')], max_length=16)),
                ('skip_reason', models.CharField(blank=True, default='', max_length=255)),
                ('error_message', models.TextField(blank=True, default='')),
                ('new_urls_1h', models.PositiveIntegerField(default=0)),
                ('new_urls_24h', models.FloatField(default=0)),
                ('unique_urls_total', models.PositiveIntegerField(default=0)),
                ('events_1h', models.PositiveIntegerField(default=0)),
                ('input_urls_count', models.PositiveIntegerField(default=0)),
                ('output_rules_count', models.PositiveIntegerField(default=0)),
                ('prompt_name', models.CharField(blank=True, default='', max_length=100)),
                ('prompt_version', models.CharField(blank=True, default='', max_length=32)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_naming_runs', to='projects.project')),
            ],
            options={
                'verbose_name': 'Page naming run',
                'verbose_name_plural': 'Page naming runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LLMUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(blank=True, default='', max_length=64)),
                ('provider', models.CharField(blank=True, default='openai', max_length=32)),
                ('operation', models.CharField(blank=True, default='chat.completions.create', max_length=64)),
                ('mode', models.CharField(blank=True, default='', max_length=32)),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('prompt_name', models.CharField(blank=True, default='', max_length=100)),
                ('prompt_version', models.CharField(blank=True, default='', max_length=32)),
                ('result', models.CharField(choices=[('ok', 'OK'), ('error', 'Error')], max_length=16)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_usage_logs', to='projects.project')),
                ('page_naming_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_usage_logs', to='tracker.projectpagenamingrun')),
            ],
            options={
                'verbose_name': 'LLM usage log',
                'verbose_name_plural': 'LLM usage logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPageRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.TextField()),
                ('product_area', models.CharField(blank=True, default='', max_length=255)),
                ('product_area_short_name', models.CharField(blank=True, default='', max_length=64)),
                ('area_role', models.CharField(choices=[('product', 'Product'), ('setup', 'Setup'), ('admin', 'Admin'), ('support', 'Support'), ('system', 'System'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('is_adoption_recommendable', models.BooleanField(default=False)),
                ('page_name', models.CharField(max_length=255)),
                ('priority', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(choices=[('hourly_unstable', 'Hourly unstable'), ('daily_stable', 'Daily stable'), ('hourly_backfill', 'Hourly title backfill')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_rules', to='projects.project')),
            ],
            options={
                'verbose_name': 'Page naming pattern',
                'verbose_name_plural': 'Page naming patterns',
                'ordering': ['-priority', '-updated_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(default='click', max_length=32)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('visitor_guid', models.UUIDField(blank=True, null=True)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('company_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user_traits', models.JSONField(blank=True, default=dict)),
                ('company_traits', models.JSONField(blank=True, default=dict)),
                ('element_key', models.CharField(blank=True, max_length=300, null=True)),
                ('url', models.TextField(blank=True, default='')),
                ('url_normalized', models.TextField(blank=True, default='')),
                ('product_area', models.CharField(blank=True, default='', max_length=255)),
                ('page_name', models.CharField(default='Undefined', max_length=255)),
                ('page_name_original', models.CharField(blank=True, default='', max_length=255)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tracker.analyticssession')),
                ('page_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='tracker.projectpagerule')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPageRuleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('hourly_unstable', 'Hourly unstable'), ('daily_stable', 'Daily stable'), ('hourly_backfill', 'Hourly title backfill')], max_length=32)),
                ('phase', models.CharField(blank=True, choices=[('bootstrap', 'Bootstrap'), ('incremental', 'Incremental'), ('stable', 'Stable'), ('backfill', 'Backfill')], default='', max_length=16)),
                ('rules_json', models.JSONField(blank=True, default=list)),
                ('ai_response_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_rule_versions', to='projects.project')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_versions', to='tracker.projectpagenamingrun')),
            ],
            options={
                'verbose_name': 'Page naming rule version',
                'verbose_name_plural': 'Page naming rule versions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True, default='')),
                ('tab_id', models.CharField(help_text='Unique browser tab identifier', max_length=36, null=True)),
                ('event_type', models.PositiveSmallIntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', models.JSONField()),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tracker.session')),
            ],
        ),
        migrations.CreateModel(
            name='BubbleCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(verbose_name='Hour and Minute')),
                ('size', models.PositiveSmallIntegerField(verbose_name='Bubble size')),
                ('clicks', models.PositiveSmallIntegerField(verbose_name='Click count')),
                ('mouse_moves', models.PositiveSmallIntegerField(verbose_name='Mouse movements')),
                ('key_strokes', models.PositiveSmallIntegerField(verbose_name='Key strokes')),
                ('seconds_spent', models.PositiveIntegerField(default=0, verbose_name='Seconds spent on page')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bubbles', to='tracker.session')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('visitor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visitor_guid', models.UUIDField(blank=True, help_text='Visitor ID from browser', null=True)),
                ('first_visit', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='visitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tracker.visitor'),
        ),
        migrations.AddIndex(
            model_name='analyticssession',
            index=models.Index(fields=['project', 'visitor_guid', 'user_id', 'company_id', 'ended_at'], name='tracker_anas_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticssession',
            index=models.Index(fields=['project', 'last_activity'], name='tracker_anas_activity_idx'),
        ),
        migrations.AddIndex(
            model_name='projectpagenamingrun',
            index=models.Index(fields=['project', 'started_at'], name='trk_pnr_proj_start_idx'),
        ),
        migrations.AddIndex(
            model_name='llmusagelog',
            index=models.Index(fields=['project', 'created_at'], name='trk_llm_proj_created_idx'),
        ),
        migrations.AddIndex(
            model_name='llmusagelog',
            index=models.Index(fields=['feature', 'created_at'], name='trk_llm_feat_created_idx'),
        ),
        migrations.AddIndex(
            model_name='llmusagelog',
            index=models.Index(fields=['result', 'created_at'], name='trk_llm_res_created_idx'),
        ),
        migrations.AddIndex(
            model_name='llmusagelog',
            index=models.Index(fields=['page_naming_run', 'created_at'], name='trk_llm_run_created_idx'),
        ),
        migrations.AddIndex(
            model_name='projectpagerule',
            index=models.Index(fields=['project', 'is_active', 'priority'], name='tracker_pgr_project_active_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['session', 'timestamp'], name='tracker_anae_session_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['visitor_guid', 'timestamp'], name='tracker_anae_visitor_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['timestamp'], name='tracker_anae_timestamp_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['url', 'timestamp'], name='trk_anae_url_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='projectpageruleversion',
            index=models.Index(fields=['project', 'created_at'], name='trk_prv_proj_created_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['session', 'timestamp'], name='trk_event_sess_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['session', 'url'], name='trk_event_sess_url_idx'),
        ),
        migrations.AddIndex(
            model_name='bubblecache',
            index=models.Index(fields=['session', 'timestamp'], name='trk_bcache_sess_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='bubblecache',
            index=models.Index(fields=['session', 'url'], name='trk_bcache_sess_url_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='visitor',
            unique_together={('visitor_guid', 'project')},
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['start_time'], name='trk_session_start_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['visitor', 'start_time'], name='trk_sess_visit_start_idx'),
        ),
    ]
