# Generated by Django 5.0.2 on 2025-07-14 11:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='session',
            name='project',
        ),
        migrations.RemoveField(
            model_name='session',
            name='source_url',
        ),
        migrations.AddField(
            model_name='bubblecache',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bubbles', to='tracker.session'),
        ),
        migrations.AddField(
            model_name='event',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tracker.session'),
        ),
        migrations.AddField(
            model_name='event',
            name='tab_id',
            field=models.CharField(help_text='Unique browser tab identifier', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.URLField(unique=True),
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('visitor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_visit', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='visitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tracker.visitor'),
        ),
        migrations.RemoveField(
            model_name='page',
            name='session',
        ),
    ]
