# Generated by Django 5.0.2 on 2025-07-31 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_page_unique_together_remove_session_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tab_id',
            field=models.CharField(help_text='Unique browser tab identifier', max_length=36, null=True),
        ),
    ]
