# Generated by Django 5.0.2 on 2025-07-31 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_safeinputregextemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(max_length=10),
        ),
    ]
