# Generated by Django 5.0.2 on 2025-07-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_event_event_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='safeinputregextemplate',
            options={'ordering': ['the_order', 'name']},
        ),
        migrations.AddField(
            model_name='safeinputregextemplate',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='safeinputregextemplate',
            name='the_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
