# Generated by Django 5.0.2 on 2025-08-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='safeinputregextemplate',
            name='replacing_code',
            field=models.TextField(default=''),
        ),
    ]
