# Generated by Django 5.0.2 on 2025-09-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_safeinputregextemplate_replacing_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='safeinputregextemplate',
            name='keep_prefix_chars',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of characters to keep visible at start'),
        ),
        migrations.AddField(
            model_name='safeinputregextemplate',
            name='keep_prefix_digits',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of digits to keep visible at start'),
        ),
        migrations.AddField(
            model_name='safeinputregextemplate',
            name='keep_suffix_chars',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of characters to keep visible at end (NOT RECOMMENDED for security)'),
        ),
        migrations.AddField(
            model_name='safeinputregextemplate',
            name='mask_type',
            field=models.CharField(choices=[('prefix_only', 'Keep prefix only (most secure)'), ('prefix_suffix', 'Keep prefix and suffix (less secure)'), ('custom', 'Use replacing_code (legacy)')], default='custom', help_text='Masking strategy to use', max_length=20),
        ),
    ]
