# Generated by Django 5.0.2 on 2025-09-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_remove_unused_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='safeinputregextemplate',
            name='keep_suffix_chars',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of characters to keep visible at end (NOT RECOMMENDED for security)'),
        ),
        migrations.AlterField(
            model_name='safeinputregextemplate',
            name='mask_type',
            field=models.CharField(choices=[('prefix_only', 'Keep prefix only (most secure)'), ('prefix_suffix', 'Keep prefix and suffix (less secure)')], default='custom', help_text='Masking strategy to use', max_length=20),
        ),
    ]
