from django.urls import path

from apps.pages import views as pages_views
from apps.projects import (
    company_attribute_filter_views,
    company_attribute_views,
    company_segment_views,
    views,
)
from apps.projects.url_helpers import project_pk_slug_view, project_slug_view, workspace_slug_view
from apps.tracker import views as tracker_views


app_name = 'w'

urlpatterns = [
    path('<slug:workspace_slug>/settings/details', workspace_slug_view(views.workspace_details), name='workspace_details'),
    path(
        '<slug:workspace_slug>/settings/details/update',
        workspace_slug_view(views.update_workspace_details),
        name='update_workspace_details',
    ),
    path(
        '<slug:workspace_slug>/settings/details/update-name',
        workspace_slug_view(views.update_workspace_name),
        name='update_workspace_name',
    ),
    path(
        '<slug:workspace_slug>/settings/details/update-slug',
        workspace_slug_view(views.update_workspace_slug),
        name='update_workspace_slug',
    ),
    path(
        '<slug:workspace_slug>/settings/details/update-website',
        workspace_slug_view(views.update_workspace_website),
        name='update_workspace_website',
    ),
    path(
        '<slug:workspace_slug>/settings/details/openai-key',
        workspace_slug_view(views.save_workspace_openai_key),
        name='save_workspace_openai_key',
    ),
    path(
        '<slug:workspace_slug>/settings/details/openai-key/validate',
        workspace_slug_view(views.validate_workspace_openai_key_view),
        name='validate_workspace_openai_key',
    ),
    path(
        '<slug:workspace_slug>/settings/details/openai-key/remove',
        workspace_slug_view(views.remove_workspace_openai_key),
        name='remove_workspace_openai_key',
    ),
    path('<slug:workspace_slug>/settings/team', workspace_slug_view(views.workspace_team), name='workspace_team'),
    path(
        '<slug:workspace_slug>/settings/team/add',
        workspace_slug_view(views.workspace_add_member),
        name='workspace_add_member',
    ),
    path(
        '<slug:workspace_slug>/settings/team/leave',
        workspace_slug_view(views.leave_workspace),
        name='leave_workspace',
    ),
    path(
        '<slug:workspace_slug>/settings/details/delete',
        workspace_slug_view(views.delete_workspace),
        name='delete_workspace',
    ),
    path(
        '<slug:workspace_slug>/settings/team/members/<int:membership_id>/remove',
        workspace_slug_view(views.remove_workspace_member),
        name='remove_workspace_member',
    ),
    path(
        '<slug:workspace_slug>/settings/team/members/<int:membership_id>/role',
        workspace_slug_view(views.update_workspace_member_role),
        name='update_workspace_member_role',
    ),
    path(
        '<slug:workspace_slug>/projects/<int:project_id>/overview',
        project_slug_view(pages_views.project_pages),
        name='project_overview',
    ),
    path(
        '<slug:workspace_slug>/projects/<int:project_id>/pages',
        project_slug_view(pages_views.project_pages),
        name='project_pages',
    ),
    path(
        '<slug:workspace_slug>/projects/<int:project_id>/pages/table-data',
        project_slug_view(pages_views.project_pages_table_data),
        name='project_pages_table_data',
    ),
    path(
        '<slug:workspace_slug>/projects/<int:project_id>/pages/scatter-tooltips',
        project_slug_view(pages_views.scatter_tooltips),
        name='project_pages_scatter_tooltips',
    ),
    path(
        '<slug:workspace_slug>/projects/<int:project_id>/pages/<str:page_rule_id>/metric-dynamics',
        project_slug_view(pages_views.project_page_metric_dynamics),
        name='project_page_metric_dynamics',
    ),
    path(
        '<slug:workspace_slug>/projects/<int:project_id>/pages/<str:page_rule_id>/table-data',
        project_slug_view(pages_views.project_page_detail_table_data),
        name='project_page_detail_table_data',
    ),
    path(
        '<slug:workspace_slug>/projects/<int:project_id>/pages/<str:page_rule_id>',
        project_slug_view(pages_views.project_page_detail),
        name='project_page_detail',
    ),
    path(
        '<slug:workspace_slug>/projects/<int:project_id>/companies',
        project_slug_view(views.project_companies),
        name='project_companies',
    ),
    path(
        '<slug:workspace_slug>/projects/<int:project_id>/companies/table-data',
        project_slug_view(views.project_companies_table_data),
        name='project_companies_table_data',
    ),
    path(
        '<slug:workspace_slug>/projects/<int:project_id>/companies/options',
        project_slug_view(views.project_company_options),
        name='project_company_options',
    ),
    path(
        '<slug:workspace_slug>/projects/<int:project_id>/companies/<str:company_id>/metric-dynamics',
        project_slug_view(views.project_company_metric_dynamics),
        name='project_company_metric_dynamics',
    ),
    path(
        '<slug:workspace_slug>/projects/<int:project_id>/companies/<str:company_id>/table-data',
        project_slug_view(views.project_company_detail_table_data),
        name='project_company_detail_table_data',
    ),
    path(
        '<slug:workspace_slug>/projects/<int:project_id>/companies/<str:company_id>',
        project_slug_view(views.project_company_detail),
        name='project_company_detail',
    ),
    path(
        '<slug:workspace_slug>/projects/<int:project_id>/users',
        project_slug_view(views.project_users),
        name='project_users',
    ),
    path(
        '<slug:workspace_slug>/projects/<int:project_id>/users/data',
        project_slug_view(views.project_users_data),
        name='project_users_data',
    ),
    path(
        '<slug:workspace_slug>/projects/<int:project_id>/users/table-data',
        project_slug_view(views.project_users_table_data),
        name='project_users_table_data',
    ),
    path(
        '<slug:workspace_slug>/projects/<int:project_id>/users/options',
        project_slug_view(views.project_user_options),
        name='project_user_options',
    ),
    path(
        '<slug:workspace_slug>/projects/<int:project_id>/analytics/variant-status',
        project_slug_view(views.project_analytics_variant_status),
        name='project_analytics_variant_status',
    ),
    path(
        '<slug:workspace_slug>/projects/<int:project_id>/company-attribute-filter-preview',
        project_slug_view(company_attribute_filter_views.project_company_attribute_filter_preview),
        name='project_company_attribute_filter_preview',
    ),
    path(
        '<slug:workspace_slug>/projects/<int:project_id>/company-segments',
        project_slug_view(company_segment_views.project_company_segments),
        name='project_company_segments',
    ),
    path(
        '<slug:workspace_slug>/projects/<int:project_id>/company-segments/create',
        project_slug_view(company_segment_views.create_project_company_segment),
        name='create_project_company_segment',
    ),
    path(
        '<slug:workspace_slug>/projects/<int:project_id>/company-segments/<str:segment_id>/update',
        project_slug_view(company_segment_views.update_project_company_segment),
        name='update_project_company_segment',
    ),
    path(
        '<slug:workspace_slug>/projects/<int:project_id>/company-segments/<str:segment_id>/delete',
        project_slug_view(company_segment_views.delete_project_company_segment),
        name='delete_project_company_segment',
    ),
    path(
        '<slug:workspace_slug>/projects/<int:project_id>/users/<str:user_id>/table-data',
        project_slug_view(views.project_user_detail_table_data),
        name='project_user_detail_table_data',
    ),
    path(
        '<slug:workspace_slug>/projects/<int:project_id>/users/<str:user_id>',
        project_slug_view(views.project_user_detail),
        name='project_user_detail',
    ),
    path(
        '<slug:workspace_slug>/projects/<int:project_id>/settings/setup',
        project_slug_view(views.project_settings),
        name='project_settings',
    ),
    path(
        '<slug:workspace_slug>/projects/<int:project_id>/settings',
        project_slug_view(views.project_settings),
        name='legacy_project_settings',
    ),
    path(
        '<slug:workspace_slug>/projects/<int:project_id>/settings/company-attributes',
        project_slug_view(company_attribute_views.project_company_attributes),
        name='project_company_attributes',
    ),
    path(
        '<slug:workspace_slug>/projects/<int:project_id>/settings/company-attributes/table-data',
        project_slug_view(company_attribute_views.project_company_attributes_table_data),
        name='project_company_attributes_table_data',
    ),
    path(
        '<slug:workspace_slug>/projects/<int:project_id>/settings/company-attributes/definitions',
        project_slug_view(company_attribute_views.save_project_company_attributes),
        name='save_project_company_attributes',
    ),
    path(
        '<slug:workspace_slug>/projects/<int:project_id>/settings/company-attributes/companies/<str:company_id>/values',
        project_slug_view(company_attribute_views.save_project_company_attribute_values),
        name='save_project_company_attribute_values',
    ),
    path(
        '<slug:workspace_slug>/projects/<int:project_id>/settings/product-areas',
        project_slug_view(views.project_product_areas),
        name='project_product_areas',
    ),
    path(
        '<slug:workspace_slug>/projects/<int:project_id>/settings/product-areas/update-guidance',
        project_slug_view(views.update_page_structure_guidance),
        name='update_page_structure_guidance',
    ),
    path(
        '<slug:workspace_slug>/projects/<int:project_id>/update-name',
        project_slug_view(views.update_project_name),
        name='update_project_name',
    ),
    path(
        '<slug:workspace_slug>/projects/<int:project_id>/update-timezone',
        project_slug_view(views.update_project_timezone),
        name='update_project_timezone',
    ),
    path(
        '<slug:workspace_slug>/projects/<int:project_id>/update-product-url',
        project_slug_view(views.update_project_product_url),
        name='update_project_product_url',
    ),
    path(
        '<slug:workspace_slug>/projects/<int:project_id>/update-tracking',
        project_slug_view(views.update_project_tracking),
        name='update_project_tracking',
    ),
    path(
        '<slug:workspace_slug>/projects/<int:pk>/delete',
        project_pk_slug_view(views.project_delete),
        name='project_delete',
    ),
    path(
        '<slug:workspace_slug>/projects/<int:project_id>/visits',
        project_slug_view(tracker_views.recordings),
        name='recordings',
    ),
    path(
        '<slug:workspace_slug>/projects/<int:project_id>/visits/filter-options',
        project_slug_view(tracker_views.visits_filter_options),
        name='visits_filter_options',
    ),
    path(
        '<slug:workspace_slug>/projects/<int:project_id>/visits/<uuid:session_id>/data',
        project_slug_view(tracker_views.get_consolidated_data),
        name='get_consolidated_data',
    ),
    path(
        '<slug:workspace_slug>/projects/<int:project_id>/visits/<uuid:session_id>/stream',
        project_slug_view(tracker_views.replay_stream),
        name='replay_stream',
    ),
    path(
        '<slug:workspace_slug>/projects/<int:project_id>/visits/<uuid:session_id>',
        project_slug_view(tracker_views.recording),
        name='recording',
    ),
]
