# Generated by Django 6.0.4 on 2026-08-06 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        ('projects', '0002_project_analytics_facts_revision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesoverviewcache',
            name='payload_compressed',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PagesCompanyAnalyticsManifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_key', models.CharField(max_length=64)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('analytics_facts_revision', models.PositiveBigIntegerField()),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('payload_format', models.CharField(default='json', max_length=32)),
                ('company_count', models.PositiveIntegerField(default=0)),
                ('payload_bytes', models.PositiveBigIntegerField(default=0)),
                ('source_max_event_ts', models.DateTimeField(blank=True, null=True)),
                ('generated_at', models.DateTimeField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages_company_analytics_manifests', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='PagesCompanyAnalyticsFragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_key', models.CharField(max_length=255)),
                ('company_id', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name_sample', models.CharField(blank=True, default='', max_length=255)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('payload_binary', models.BinaryField(blank=True, null=True)),
                ('payload_bytes', models.PositiveBigIntegerField(default=0)),
                ('manifest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragments', to='pages.pagescompanyanalyticsmanifest')),
            ],
        ),
        migrations.AddIndex(
            model_name='pagescompanyanalyticsmanifest',
            index=models.Index(fields=['project', 'range_key', 'analytics_facts_revision'], name='pages_cmpfact_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='pagescompanyanalyticsmanifest',
            constraint=models.UniqueConstraint(fields=('project', 'range_key', 'start_date', 'end_date', 'analytics_facts_revision'), name='pages_cmpfact_manifest_uniq'),
        ),
        migrations.AddIndex(
            model_name='pagescompanyanalyticsfragment',
            index=models.Index(fields=['manifest', 'company_id'], name='pages_cmpfrag_company_idx'),
        ),
        migrations.AddIndex(
            model_name='pagescompanyanalyticsfragment',
            index=models.Index(fields=['manifest', 'company_key'], name='pages_cmpfrag_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='pagescompanyanalyticsfragment',
            constraint=models.UniqueConstraint(fields=('manifest', 'company_key'), name='pages_cmpfrag_key_uniq'),
        ),
    ]
